### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by darkshadow22722** [jzarca01/fetch-my-whopper#1]
/home/user/fetch-my-whopper/index.js:14
app.post('/whopper', async (req, res) => {
                           ^
SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)

**Comment by darkshadow22722** [comment]
I resolved using node v 8
